#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2015 OpenWrt.org

USE_PROCD=1
START=99
STOP=90

start_service() {
    # 加载配置
    config_load "vlmcsd"
    
    # 获取启用状态的配置值
    config_get enable_value config enable 0
    if [ "$enable_value" -eq 0 ]; then
        echo "KMS Server is disabled, not starting."
        exit 0
    fi

    # 获取端口配置值
    config_get port_value vlmcsd port 1688

    # 启动服务
    procd_open_instance
    procd_set_param command /usr/bin/vlmcsd
    procd_append_param command -i /etc/vlmcsd/vlmcsd.ini
    procd_append_param command -L 0.0.0.0:$port_value
    procd_append_param command -L [::]:$port_value
    procd_close_instance
    
    echo "KMS Server has started on port $port_value."
}

stop_service() {
    killall -q vlmcsd
    echo "KMS Server has stopped."
}

reload_service() {
    stop_service
    sleep 1
    start_service
}

service_triggers() {
    # 当配置变化时，触发重新加载服务
    procd_add_reload_trigger "vlmcsd"
}
